from __future__ import annotations
import time
import logging
from typing import Optional, List, Dict, Any, Callable, Literal
from pydantic import BaseModel, Field

from desktop_dom.schema import DesktopNode
from desktop_dom.app import DesktopApp
from desktop_dom.diff import DOMDiff, ActionResult, compute_dom_diff

logger = logging.getLogger("desktop_dom.agent")

class AgentAction(BaseModel):
    """Atomic plan item generated by the agent planner."""
    action_type: Literal["click", "type", "press", "wait", "finish", "fail"] = Field(
        description="Action verb to execute"
    )
    target_id: Optional[str] = Field(default=None, description="Element ID to target")
    target_role: Optional[str] = Field(default=None, description="Element role selector fallback")
    target_name: Optional[str] = Field(default=None, description="Element name/label selector fallback")
    text: Optional[str] = Field(default=None, description="Text to type if action_type is 'type'")
    key: Optional[str] = Field(default=None, description="Key chord if action_type is 'press'")
    expected_effect: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Expected DOM mutation for verification (e.g. {'type': 'any_change'})")
    reasoning: str = Field(default="", description="Explanation of why this action advances the goal")


class AgentStep(BaseModel):
    """Record of a single ReAct cycle execution."""
    step_number: int
    action: AgentAction
    result: ActionResult
    reflection: str = Field(default="", description="Self-correction assessment after verifying T1 - T0 diff")
    elapsed_ms: float = 0.0


class AgentResult(BaseModel):
    """Comprehensive summary of an autonomous agent execution run."""
    goal: str
    status: Literal["completed", "failed", "max_steps_exceeded"]
    steps: List[AgentStep] = Field(default_factory=list)
    total_elapsed_ms: float = 0.0
    summary: str = ""

    @property
    def is_successful(self) -> bool:
        return self.status == "completed"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "goal": self.goal,
            "status": self.status,
            "steps_count": len(self.steps),
            "total_elapsed_ms": round(self.total_elapsed_ms, 2),
            "summary": self.summary,
            "steps": [
                {
                    "step": s.step_number,
                    "action": s.action.action_type,
                    "target": s.action.target_id or s.action.target_name,
                    "verified": s.result.verified,
                    "reflection": s.reflection,
                    "diff": s.result.diff.to_dict(),
                }
                for s in self.steps
            ],
        }


class AutonomousDesktopAgent:
    """
    Level 3 Autonomous Desktop Agent.
    Implements a closed-loop ReAct cycle with T1 - T0 DOM diff state verification:
      1. Observe: Capture current desktop DOM snapshot (T0).
      2. Plan: Synthesize next atomic action using deterministic rules or pluggable LLM.
      3. Act & Verify: Dispatch action and capture resulting DOM mutations (T1 - T0).
      4. Reflect: Verify whether intended state change occurred; if not, self-correct.
      5. Terminate: Halt when goal is verified complete or retry limit is hit.
    """

    def __init__(
        self,
        app: DesktopApp,
        max_steps: int = 10,
        planner_fn: Optional[Callable[[str, DesktopNode, List[AgentStep]], AgentAction]] = None,
        settle_delay: float = 0.05,
    ):
        self.app = app
        self.max_steps = max_steps
        self.planner_fn = planner_fn or self._default_deterministic_planner
        self.settle_delay = settle_delay
        self.history: List[AgentStep] = []

    def run(self, goal: str) -> AgentResult:
        """
        Executes the autonomous agentic loop towards the specified user goal.
        """
        start_time = time.perf_counter()
        self.history.clear()
        logger.info(f"Starting Level 3 Autonomous Loop for goal: {goal!r}")

        consecutive_misses = 0

        for step_idx in range(1, self.max_steps + 1):
            step_start = time.perf_counter()

            # 1. OBSERVE (T0)
            current_tree = self.app.snapshot()

            # 2. PLAN
            action = self.planner_fn(goal, current_tree, self.history)

            # Check for terminal actions
            if action.action_type == "finish":
                total_ms = (time.perf_counter() - start_time) * 1000.0
                return AgentResult(
                    goal=goal,
                    status="completed",
                    steps=self.history,
                    total_elapsed_ms=total_ms,
                    summary=f"Goal completed successfully in {len(self.history)} steps: {action.reasoning}",
                )

            if action.action_type == "fail":
                total_ms = (time.perf_counter() - start_time) * 1000.0
                return AgentResult(
                    goal=goal,
                    status="failed",
                    steps=self.history,
                    total_elapsed_ms=total_ms,
                    summary=f"Agent could not satisfy goal: {action.reasoning}",
                )

            # 3. ACT & VERIFY (T1 - T0)
            action_result = self._dispatch_action(action)
            step_ms = (time.perf_counter() - step_start) * 1000.0

            # 4. REFLECT & SELF-CORRECT
            reflection = ""
            if not action_result.verified:
                consecutive_misses += 1
                reflection = (
                    f"Step {step_idx}: Action '{action.action_type}' produced no verified mutation. "
                    f"Consecutive misses: {consecutive_misses}. Attempting recovery on next cycle."
                )
                logger.warning(reflection)
                if consecutive_misses >= 3:
                    # Stuck loop mitigation: force a refresh and small wait
                    time.sleep(0.2)
            else:
                consecutive_misses = 0
                reflection = (
                    f"Step {step_idx}: Action '{action.action_type}' verified. {action_result.diff.summary}"
                )

            step_record = AgentStep(
                step_number=step_idx,
                action=action,
                result=action_result,
                reflection=reflection,
                elapsed_ms=step_ms,
            )
            self.history.append(step_record)

        total_ms = (time.perf_counter() - start_time) * 1000.0
        return AgentResult(
            goal=goal,
            status="max_steps_exceeded",
            steps=self.history,
            total_elapsed_ms=total_ms,
            summary=f"Exceeded maximum step budget ({self.max_steps}) without reaching terminal state",
        )

    def _dispatch_action(self, action: AgentAction) -> ActionResult:
        """Dispatches the planned action wrapped in state verification."""
        target_id = action.target_id

        # If target_id not provided but role/name given, resolve it dynamically
        if not target_id and (action.target_role or action.target_name):
            match = self.app.find(role=action.target_role, name=action.target_name)
            if match:
                target_id = match.id

        expected = action.expected_effect or {"type": "any_change"}

        if action.action_type == "click":
            if not target_id:
                # No target to click
                diff = DOMDiff()
                return ActionResult(
                    action="click",
                    status="failed",
                    diff=diff,
                    verified=False,
                    verification_message="Cannot click: target element ID could not be resolved",
                    error="Unresolved target ID",
                )
            return self.app.execute_and_verify(
                action_fn=lambda: self.app.click(target_id),
                expected_effect=expected,
                settle_delay=self.settle_delay,
            )

        elif action.action_type == "type":
            text = action.text or ""
            return self.app.execute_and_verify(
                action_fn=lambda: self.app.type(target_id, text),
                expected_effect=expected,
                settle_delay=self.settle_delay,
            )

        elif action.action_type == "press":
            key = action.key or "return"
            return self.app.execute_and_verify(
                action_fn=lambda: self.app.press(key),
                expected_effect=expected,
                settle_delay=self.settle_delay,
            )

        elif action.action_type == "wait":
            time.sleep(self.settle_delay * 2)
            diff = DOMDiff()
            return ActionResult(
                action="wait",
                status="success",
                diff=diff,
                verified=True,
                verification_message="Wait completed",
            )

        diff = DOMDiff()
        return ActionResult(
            action=action.action_type,
            status="failed",
            diff=diff,
            verified=False,
            verification_message=f"Unsupported action type: {action.action_type}",
        )

    def _default_deterministic_planner(
        self,
        goal: str,
        tree: DesktopNode,
        history: List[AgentStep],
    ) -> AgentAction:
        """
        Deterministic goal decomposition engine for common desktop workflows.
        Executes without external LLM dependencies, ensuring 100% hermetic offline testing.
        """
        goal_lower = goal.lower()

        # Check if previous step finished the goal
        if history:
            last_step = history[-1]
            # If last action was typing or pressing return on a search/email, and diff showed changes, finish
            if last_step.action.action_type in ("press", "type") and last_step.result.verified:
                # If we achieved the goal, terminate
                if len(history) >= 2 or "search" in goal_lower or "type" in goal_lower:
                    return AgentAction(action_type="finish", reasoning="Action verified and goal completed")

        # Search workflow: 'search for <term>'
        if "search" in goal_lower:
            search_input = tree.find_all(role="input")
            if search_input:
                target = search_input[0]
                # If we haven't typed yet, plan typing
                if not any(s.action.action_type == "type" for s in history):
                    term = goal.split("for", 1)[-1].strip() if "for" in goal_lower else "query"
                    return AgentAction(
                        action_type="type",
                        target_id=target.id,
                        text=term,
                        reasoning=f"Typing search query '{term}' into input field '{target.id}'",
                        expected_effect={"type": "value_changed", "id": target.id},
                    )
                else:
                    return AgentAction(
                        action_type="press",
                        key="return",
                        reasoning="Submitting search via Return key",
                        expected_effect={"type": "any_change"},
                    )

        # Click workflow: 'click <button name>'
        if "click" in goal_lower:
            parts = goal.split("click", 1)[-1].strip().strip("'").strip('"')
            button = tree.find_all(role="button", name=parts)
            if button:
                return AgentAction(
                    action_type="click",
                    target_id=button[0].id,
                    reasoning=f"Clicking requested button '{button[0].name}' ({button[0].id})",
                    expected_effect={"type": "any_change"},
                )
            all_buttons = tree.find_all(role="button")
            if all_buttons:
                return AgentAction(
                    action_type="click",
                    target_id=all_buttons[0].id,
                    reasoning=f"Clicking first available button '{all_buttons[0].name}' ({all_buttons[0].id})",
                    expected_effect={"type": "any_change"},
                )

        # Default fallback: if buttons exist, click first actionable element, else finish
        actionable = [n for n in tree.flatten() if n.states.is_actionable and n.role in ("button", "input")]
        if actionable and len(history) < 2:
            first = actionable[0]
            if first.role == "button":
                return AgentAction(
                    action_type="click",
                    target_id=first.id,
                    reasoning=f"Interacting with actionable element '{first.name}'",
                    expected_effect={"type": "any_change"},
                )
            elif first.role == "input":
                return AgentAction(
                    action_type="type",
                    target_id=first.id,
                    text="test",
                    reasoning=f"Entering value into input '{first.name}'",
                    expected_effect={"type": "value_changed", "id": first.id},
                )

        return AgentAction(action_type="finish", reasoning="Tree analyzed, goal completed")
